### PR TITLE
Add transaction data to payment

### PR DESCRIPTION
**Pull request by CJentzsch**
Since this vault should be generic, it is important that it can call functions in other contracts(project tracker, milestone contracts ...)

### CODE REVIEW

**Comment by jbaylina** [comment]
Again, We had this functionality in the beginning and then we decided to remove it. This is a communications decision (not a technical decision). It seems more easy to  "sell" this contract with `send` that with a `call`. 
Also, the idea of this contract is to make a formal verification. 
@GriffGreen and @barryWhiteHat I would like to here your opinions on this.

**Comment by GriffGreen** [comment]
This is absolutely true and Jordi had this initially set in place, but the PR strategy is to be ultra security conscious and as we evolve as we need. If this functionality is needed we will add it... but i am also sure it would be easy to have a manual work around until everything is really developed. The fact is, the call function is something that I would have to defend for days on reddit and it could make people lose trust in the platform. It just can't happen right away, but eventually we will have the call function for sure. :-)

**Comment by CJentzsch** [comment]
I understand your point, but this sounds like `call` is always a bad thing. 
The problem with `call` is, that per default it sends all gas, therefore it allows for reentry.
But this can be prevented with a mutex ( `payment.paid`) and the fixed gas amount (although this need to be double checked, since one may be able to use a gas refund with SSTORE to overcome this).
I think we should look at those contracts from a purely technical angle.
The main problem with send is, that really can't call functions in other contracts with it. Most default function actually throw when money is send to them, since they are not payable. This mean we only send to multisigs, normal accounts and a few other contract prepared to receive funds in there default function without acting on it.

**Comment by GriffGreen** [comment]
We are taking a very scared squirrel approach here, for the first iteration the call function is more trouble then it's worth, and the second that someone actually needs to call a contract, we will add it back in, but this initial set up is designed to be very manual, not automated in any way. 

If for instance we need the call function to coordinate with CharityDAO then its easy enough to add that at that time... but for this first iteration, it isn't needed, what is needed is that people can trust us to take every effort to go the extra mile for security in our smart contracts.

The contract is extremely upgradeable so when it is needed, don't worry it will be there. :-)

**Comment by jbaylina** [comment]
Let me give you two arguments that helped to auto-convince myself why to remove the `call`:
1.- The PR argument is not technical but that don't mean that it is not important. 
2.- A vault can only do payments. (It is not an entity like a DAO that can do any thing). Read a payment as a `send` and do any thing is a `call`
A possible structure, that I'm thinking is in a Recipient of this form:

contract Recipient {
 
   function collectEtherAndStartACampaig(uint _idPayment) {
      vault.executePayment(_idPayment)
      startCampaign();
   }

   function startCampaign() internal {
      // Triggered when ether is received.
      // Do all the calls necessary to start the campaign
  }

}

in this situation, the Reception contract can make the calls he wants in .

Thats why als is better to not accept any one to recive the send. ( https://github.com/Giveth/vaultcontract/pull/3 ) This way we waranty that we can trigger any thing when we receive the trigger.

And said that, I'll accept any of the two options. :)

**Comment by CJentzsch** [comment]
ok, this is a valid solution. 
I trust you @GriffGreen that when you see the community demands it, than so be it.

**Pull request closed without merging**
